<?php

/**
 * BaseForumBigTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property integer $team_id
 * @property Team $Team
 * @property Doctrine_Collection $Topics
 * 
 * @method string              getTitle()   Returns the current record's "title" value
 * @method integer             getTeamId()  Returns the current record's "team_id" value
 * @method Team                getTeam()    Returns the current record's "Team" value
 * @method Doctrine_Collection getTopics()  Returns the current record's "Topics" collection
 * @method ForumBigTopic       setTitle()   Sets the current record's "title" value
 * @method ForumBigTopic       setTeamId()  Sets the current record's "team_id" value
 * @method ForumBigTopic       setTeam()    Sets the current record's "Team" value
 * @method ForumBigTopic       setTopics()  Sets the current record's "Topics" collection
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForumBigTopic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forum_big_topic');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ForumTopic as Topics', array(
             'local' => 'id',
             'foreign' => 'big_topic_id'));
    }
}