<?php

/**
 * BaseUserTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $team_id
 * @property boolean $is_captain
 * @property Team $Team
 * 
 * @method integer  getUserId()     Returns the current record's "user_id" value
 * @method integer  getTeamId()     Returns the current record's "team_id" value
 * @method boolean  getIsCaptain()  Returns the current record's "is_captain" value
 * @method Team     getTeam()       Returns the current record's "Team" value
 * @method UserTeam setUserId()     Sets the current record's "user_id" value
 * @method UserTeam setTeamId()     Sets the current record's "team_id" value
 * @method UserTeam setIsCaptain()  Sets the current record's "is_captain" value
 * @method UserTeam setTeam()       Sets the current record's "Team" value
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_team');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_captain', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}