<?php

/**
 * BaseBigTopicCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $BigTopics
 * 
 * @method string              getTitle()     Returns the current record's "title" value
 * @method Doctrine_Collection getBigTopics() Returns the current record's "BigTopics" collection
 * @method BigTopicCategory    setTitle()     Sets the current record's "title" value
 * @method BigTopicCategory    setBigTopics() Sets the current record's "BigTopics" collection
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBigTopicCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('f_big_topic_category');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BigTopic as BigTopics', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}