<?php

/**
 * BaseTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property enum $type
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Sessions
 * @property Doctrine_Collection $TeamUsers
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method enum                getType()      Returns the current record's "type" value
 * @method Doctrine_Collection getUsers()     Returns the current record's "Users" collection
 * @method Doctrine_Collection getSessions()  Returns the current record's "Sessions" collection
 * @method Doctrine_Collection getTeamUsers() Returns the current record's "TeamUsers" collection
 * @method Team                setName()      Sets the current record's "name" value
 * @method Team                setType()      Sets the current record's "type" value
 * @method Team                setUsers()     Sets the current record's "Users" collection
 * @method Team                setSessions()  Sets the current record's "Sessions" collection
 * @method Team                setTeamUsers() Sets the current record's "TeamUsers" collection
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'enum', 5, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'PH - Championnat de Paris',
              1 => 'PR - Championnat départemental',
              2 => 'D2 - Championnat départemental',
              3 => 'D2 - Championnat de Paris',
              4 => 'D3 - Championnat départemental',
             ),
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'UserTeam',
             'local' => 'team_id',
             'foreign' => 'user_name'));

        $this->hasMany('CompetitionSessionTeam as Sessions', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('UserTeam as TeamUsers', array(
             'local' => 'id',
             'foreign' => 'team_id'));
    }
}