<?php

/**
 * BaseInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $company
 * @property string $address
 * @property string $city
 * @property string $zipcode
 * @property string $phone
 * @property string $fullname
 * @property string $email
 * 
 * @method string getCompany()  Returns the current record's "company" value
 * @method string getAddress()  Returns the current record's "address" value
 * @method string getCity()     Returns the current record's "city" value
 * @method string getZipcode()  Returns the current record's "zipcode" value
 * @method string getPhone()    Returns the current record's "phone" value
 * @method string getFullname() Returns the current record's "fullname" value
 * @method string getEmail()    Returns the current record's "email" value
 * @method Info   setCompany()  Sets the current record's "company" value
 * @method Info   setAddress()  Sets the current record's "address" value
 * @method Info   setCity()     Sets the current record's "city" value
 * @method Info   setZipcode()  Sets the current record's "zipcode" value
 * @method Info   setPhone()    Sets the current record's "phone" value
 * @method Info   setFullname() Sets the current record's "fullname" value
 * @method Info   setEmail()    Sets the current record's "email" value
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('info');
        $this->hasColumn('company', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('zipcode', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fullname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}