<?php

/**
 * BaseKeyword
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $reference
 * @property Doctrine_Collection $Articles
 * @property Doctrine_Collection $ArticleKeywords
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getReference()       Returns the current record's "reference" value
 * @method Doctrine_Collection getArticles()        Returns the current record's "Articles" collection
 * @method Doctrine_Collection getArticleKeywords() Returns the current record's "ArticleKeywords" collection
 * @method Keyword             setName()            Sets the current record's "name" value
 * @method Keyword             setReference()       Sets the current record's "reference" value
 * @method Keyword             setArticles()        Sets the current record's "Articles" collection
 * @method Keyword             setArticleKeywords() Sets the current record's "ArticleKeywords" collection
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKeyword extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('keyword');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('reference', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Article as Articles', array(
             'refClass' => 'ArticleKeyword',
             'local' => 'keyword_id',
             'foreign' => 'article_id'));

        $this->hasMany('ArticleKeyword as ArticleKeywords', array(
             'local' => 'id',
             'foreign' => 'keyword_id'));
    }
}