<?php

/**
 * BaseInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $address
 * @property string $street
 * @property string $city
 * @property string $zipcode
 * @property string $phone
 * @property string $email
 * 
 * @method string getAddress() Returns the current record's "address" value
 * @method string getStreet()  Returns the current record's "street" value
 * @method string getCity()    Returns the current record's "city" value
 * @method string getZipcode() Returns the current record's "zipcode" value
 * @method string getPhone()   Returns the current record's "phone" value
 * @method string getEmail()   Returns the current record's "email" value
 * @method Info   setAddress() Sets the current record's "address" value
 * @method Info   setStreet()  Sets the current record's "street" value
 * @method Info   setCity()    Sets the current record's "city" value
 * @method Info   setZipcode() Sets the current record's "zipcode" value
 * @method Info   setPhone()   Sets the current record's "phone" value
 * @method Info   setEmail()   Sets the current record's "email" value
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('info');
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('street', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('zipcode', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}