<?php

/**
 * BasePongScore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $playername
 * @property string $score
 * 
 * @method string    getPlayername() Returns the current record's "playername" value
 * @method string    getScore()      Returns the current record's "score" value
 * @method PongScore setPlayername() Sets the current record's "playername" value
 * @method PongScore setScore()      Sets the current record's "score" value
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePongScore extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pong_score');
        $this->hasColumn('playername', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('score', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}