<?php

/**
 * BaseTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $subtitle
 * @property integer $author_id
 * @property integer $big_topic_id
 * @property BigTopic $BigTopic
 * @property sfGuardUser $Author
 * @property Doctrine_Collection $Messages
 * 
 * @method string              getTitle()        Returns the current record's "title" value
 * @method string              getSubtitle()     Returns the current record's "subtitle" value
 * @method integer             getAuthorId()     Returns the current record's "author_id" value
 * @method integer             getBigTopicId()   Returns the current record's "big_topic_id" value
 * @method BigTopic            getBigTopic()     Returns the current record's "BigTopic" value
 * @method sfGuardUser         getAuthor()       Returns the current record's "Author" value
 * @method Doctrine_Collection getMessages()     Returns the current record's "Messages" collection
 * @method Topic               setTitle()        Sets the current record's "title" value
 * @method Topic               setSubtitle()     Sets the current record's "subtitle" value
 * @method Topic               setAuthorId()     Sets the current record's "author_id" value
 * @method Topic               setBigTopicId()   Sets the current record's "big_topic_id" value
 * @method Topic               setBigTopic()     Sets the current record's "BigTopic" value
 * @method Topic               setAuthor()       Sets the current record's "Author" value
 * @method Topic               setMessages()     Sets the current record's "Messages" collection
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTopic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('f_topic');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('subtitle', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('big_topic_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BigTopic', array(
             'local' => 'big_topic_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Author', array(
             'local' => 'author_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('TopicMessage as Messages', array(
             'local' => 'id',
             'foreign' => 'topic_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}