<?php

/**
 * BaseCompetition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Sessions
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getSessions() Returns the current record's "Sessions" collection
 * @method Competition         setName()     Sets the current record's "name" value
 * @method Competition         setSessions() Sets the current record's "Sessions" collection
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompetition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('competition');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CompetitionSession as Sessions', array(
             'local' => 'id',
             'foreign' => 'competition_id'));
    }
}