<?php

/**
 * BaseInfoElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $content
 * @property integer $position
 * 
 * @method string      getTitle()    Returns the current record's "title" value
 * @method clob        getContent()  Returns the current record's "content" value
 * @method integer     getPosition() Returns the current record's "position" value
 * @method InfoElement setTitle()    Sets the current record's "title" value
 * @method InfoElement setContent()  Sets the current record's "content" value
 * @method InfoElement setPosition() Sets the current record's "position" value
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInfoElement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('info_element');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}