<?php

/**
 * BaseCompetitionSessionTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $team_id
 * @property integer $competition_session_id
 * @property Team $Team
 * @property CompetitionSession $Session
 * 
 * @method integer                getTeamId()                 Returns the current record's "team_id" value
 * @method integer                getCompetitionSessionId()   Returns the current record's "competition_session_id" value
 * @method Team                   getTeam()                   Returns the current record's "Team" value
 * @method CompetitionSession     getSession()                Returns the current record's "Session" value
 * @method CompetitionSessionTeam setTeamId()                 Sets the current record's "team_id" value
 * @method CompetitionSessionTeam setCompetitionSessionId()   Sets the current record's "competition_session_id" value
 * @method CompetitionSessionTeam setTeam()                   Sets the current record's "Team" value
 * @method CompetitionSessionTeam setSession()                Sets the current record's "Session" value
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompetitionSessionTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('competition_session_team');
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('competition_session_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id'));

        $this->hasOne('CompetitionSession as Session', array(
             'local' => 'competition_session_id',
             'foreign' => 'id'));
    }
}