<?php

/**
 * BasescheduleCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $position
 * @property string $name
 * @property Doctrine_Collection $Days
 * 
 * @method integer             getPosition() Returns the current record's "position" value
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getDays()     Returns the current record's "Days" collection
 * @method scheduleCategory    setPosition() Sets the current record's "position" value
 * @method scheduleCategory    setName()     Sets the current record's "name" value
 * @method scheduleCategory    setDays()     Sets the current record's "Days" collection
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasescheduleCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('schedule_category');
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('scheduleDay as Days', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}