<?php

/**
 * BaseCompetitionSessionDisponibility
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $session_id
 * @property boolean $is_available
 * @property sfGuardUser $User
 * @property CompetitionSession $Session
 * 
 * @method integer                         getUserId()       Returns the current record's "user_id" value
 * @method integer                         getSessionId()    Returns the current record's "session_id" value
 * @method boolean                         getIsAvailable()  Returns the current record's "is_available" value
 * @method sfGuardUser                     getUser()         Returns the current record's "User" value
 * @method CompetitionSession              getSession()      Returns the current record's "Session" value
 * @method CompetitionSessionDisponibility setUserId()       Sets the current record's "user_id" value
 * @method CompetitionSessionDisponibility setSessionId()    Sets the current record's "session_id" value
 * @method CompetitionSessionDisponibility setIsAvailable()  Sets the current record's "is_available" value
 * @method CompetitionSessionDisponibility setUser()         Sets the current record's "User" value
 * @method CompetitionSessionDisponibility setSession()      Sets the current record's "Session" value
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompetitionSessionDisponibility extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('competition_session_disponibility');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('session_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('is_available', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('CompetitionSession as Session', array(
             'local' => 'session_id',
             'foreign' => 'id'));
    }
}