<?php

/**
 * BasePriceElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $element
 * @property string $info
 * @property string $price
 * @property integer $category_id
 * @property PriceCategory $Category
 * 
 * @method string        getElement()     Returns the current record's "element" value
 * @method string        getInfo()        Returns the current record's "info" value
 * @method string        getPrice()       Returns the current record's "price" value
 * @method integer       getCategoryId()  Returns the current record's "category_id" value
 * @method PriceCategory getCategory()    Returns the current record's "Category" value
 * @method PriceElement  setElement()     Sets the current record's "element" value
 * @method PriceElement  setInfo()        Sets the current record's "info" value
 * @method PriceElement  setPrice()       Sets the current record's "price" value
 * @method PriceElement  setCategoryId()  Sets the current record's "category_id" value
 * @method PriceElement  setCategory()    Sets the current record's "Category" value
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePriceElement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('price_element');
        $this->hasColumn('element', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('info', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('price', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PriceCategory as Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}