<?php

/**
 * BaseForumTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $author_id
 * @property integer $big_topic_id
 * @property string $title
 * @property ForumBigTopic $BigTopic
 * @property sfGuardUser $Author
 * @property Doctrine_Collection $Posts
 * 
 * @method integer             getAuthorId()     Returns the current record's "author_id" value
 * @method integer             getBigTopicId()   Returns the current record's "big_topic_id" value
 * @method string              getTitle()        Returns the current record's "title" value
 * @method ForumBigTopic       getBigTopic()     Returns the current record's "BigTopic" value
 * @method sfGuardUser         getAuthor()       Returns the current record's "Author" value
 * @method Doctrine_Collection getPosts()        Returns the current record's "Posts" collection
 * @method ForumTopic          setAuthorId()     Sets the current record's "author_id" value
 * @method ForumTopic          setBigTopicId()   Sets the current record's "big_topic_id" value
 * @method ForumTopic          setTitle()        Sets the current record's "title" value
 * @method ForumTopic          setBigTopic()     Sets the current record's "BigTopic" value
 * @method ForumTopic          setAuthor()       Sets the current record's "Author" value
 * @method ForumTopic          setPosts()        Sets the current record's "Posts" collection
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForumTopic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forum_topic');
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('big_topic_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ForumBigTopic as BigTopic', array(
             'local' => 'big_topic_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Author', array(
             'local' => 'author_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ForumPost as Posts', array(
             'local' => 'id',
             'foreign' => 'topic_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}