<?php

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $sub_title
 * @property clob $content
 * @property boolean $is_published
 * @property timestamp $published_at
 * @property string $picture
 * 
 * @method string    getTitle()        Returns the current record's "title" value
 * @method string    getSubTitle()     Returns the current record's "sub_title" value
 * @method clob      getContent()      Returns the current record's "content" value
 * @method boolean   getIsPublished()  Returns the current record's "is_published" value
 * @method timestamp getPublishedAt()  Returns the current record's "published_at" value
 * @method string    getPicture()      Returns the current record's "picture" value
 * @method Article   setTitle()        Sets the current record's "title" value
 * @method Article   setSubTitle()     Sets the current record's "sub_title" value
 * @method Article   setContent()      Sets the current record's "content" value
 * @method Article   setIsPublished()  Sets the current record's "is_published" value
 * @method Article   setPublishedAt()  Sets the current record's "published_at" value
 * @method Article   setPicture()      Sets the current record's "picture" value
 * 
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sub_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
        $this->hasColumn('published_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('picture', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}