competition:
  class: sfDoctrineRouteCollection
  options:
    model:                Competition
    module:               competition
    prefix_path:          /competition
    column:               id
    with_wildcard_routes: true

competition_session_disponibility:
  class: sfDoctrineRouteCollection
  options:
    model:                CompetitionSessionDisponibility
    module:               competition_session_disponibilty
    prefix_path:          /competition_session_disponibilty
    column:               Array
    with_wildcard_routes: true

competition_session_team:
  class: sfDoctrineRouteCollection
  options:
    model:                CompetitionSessionTeam
    module:               competition_session_team
    prefix_path:          /competition_session_team
    column:               id
    with_wildcard_routes: true

competition_session:
  class: sfDoctrineRouteCollection
  options:
    model:                CompetitionSession
    module:               competition_session
    prefix_path:          /competition_session
    column:               id
    with_wildcard_routes: true

topic_message:
  class: sfDoctrineRouteCollection
  options:
    model:                TopicMessage
    module:               topic_message
    prefix_path:          /topic_message
    column:               id
    with_wildcard_routes: true

topic:
  class: sfDoctrineRouteCollection
  options:
    model:                Topic
    module:               topic
    prefix_path:          /topic
    column:               id
    with_wildcard_routes: true

big_topic:
  class: sfDoctrineRouteCollection
  options:
    model:                BigTopic
    module:               big_topic
    prefix_path:          /big_topic
    column:               id
    with_wildcard_routes: true

big_topic_category:
  class: sfDoctrineRouteCollection
  options:
    model:                BigTopicCategory
    module:               big_topic_category
    prefix_path:          /big_topic_category
    column:               id
    with_wildcard_routes: true

info:
  class: sfDoctrineRouteCollection
  options:
    model:                Info
    module:               info
    prefix_path:          /info
    column:               id
    with_wildcard_routes: true

address:
  class: sfDoctrineRouteCollection
  options:
    model:                Address
    module:               address
    prefix_path:          /address
    column:               id
    with_wildcard_routes: true

link:
  class: sfDoctrineRouteCollection
  options:
    model:                Link
    module:               link
    prefix_path:          /link
    column:               id
    with_wildcard_routes: true

user_team:
  class: sfDoctrineRouteCollection
  options:
    model:                UserTeam
    module:               userTeam
    prefix_path:          /userTeam
    column:               id
    with_wildcard_routes: true

team:
  class: sfDoctrineRouteCollection
  options:
    model:                Team
    module:               team
    prefix_path:          /team
    column:               id
    with_wildcard_routes: true

picture:
  class: sfDoctrineRouteCollection
  options:
    model:                Picture
    module:               picture
    prefix_path:          /picture
    column:               id
    with_wildcard_routes: true

gallery:
  class: sfDoctrineRouteCollection
  options:
    model:                Gallery
    module:               gallery
    prefix_path:          /gallery
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               user
    prefix_path:          /user
    column:               id
    with_wildcard_routes: true

keyword:
  class: sfDoctrineRouteCollection
  options:
    model:                Keyword
    module:               keyword
    prefix_path:          /keyword
    column:               id
    with_wildcard_routes: true

article:
  class: sfDoctrineRouteCollection
  options:
    model:                Article
    module:               article
    prefix_path:          /article
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: sfAdminDash, action: dashboard }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
