<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/08/12 13:13:07
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => false,
  'library' => 'gd_mime_type',
),
  'app_sf_admin_dash_web_dir' => '/sfAdminDashPlugin',
  'app_sf_admin_dash_image_dir' => '/sfAdminDashPlugin/images/icons/',
  'app_sf_admin_dash_default_image' => 'config.png',
  'app_sf_admin_dash_dashboard_url' => '@homepage',
  'app_sf_admin_dash_resize_mode' => 'thumbnail',
  'app_sf_admin_dash_site' => 'My Site Name',
  'app_sf_admin_dash_include_path' => true,
  'app_sf_admin_dash_include_assets' => true,
  'app_sf_admin_dash_include_jquery' => true,
  'app_sf_admin_dash_include_jquery_no_conflict' => false,
  'app_sf_admin_dash_login_route' => '@sf_guard_signin',
  'app_sf_admin_dash_logout' => true,
  'app_sf_admin_dash_logout_route' => '@sf_guard_signout',
  'app_pagination_max_article_per_page' => 4,
  'app_sf_guard_plugin_success_signin_url' => '@homepage',
));
