sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_logout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

user_list:
  url:   /users
  param: { module: user, action: list }

user_new:
  url:   /user/new
  param: { module: user, action: new }

user_edit:
  url:   /user/edit/:id
  param: { module: user, action: edit }

user_delete:
  url:   /user/delete/:id
  param: { module: user, action: delete }

article_list:
  url:   /articles
  param: { module: article, action: list }

article_new:
  url:   /article/new
  param: { module: article, action: new }

article_edit:
  url:   /article/edit/:id
  param: { module: article, action: edit }

article_delete:
  url:   /article/delete/:id
  param: { module: article, action: delete }

team_list:
  url:   /teams
  param: { module: team, action: list }

team_new:
  url:   /team/new
  param: { module: team, action: new }

team_edit:
  url:   /team/edit/:id
  param: { module: team, action: edit }

team_delete:
  url:   /team/delete/:id
  param: { module: team, action: delete }

delete_from_team:
  url:   /team/deleteUser/:teamId/:userId
  param: { module: team, action: deleteUser }

name_captain:
  url:   /team/nameCaptain/:teamId/:userId
  param: { module: team, action: nameCaptain }

remove_captain:
  url:   /team/removeCaptain/:teamId/:userId
  param: { module: team, action: removeCaptain }


add_team_user:
  url:   /team/addTeamUser/:teamId/:userId
  param: { module: team, action: addTeamUser }


# default rules
homepage:
  url:   /
  param: { module: homepage, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
