sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_logout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

user_list:
  url:   /users
  param: { module: user, action: list }

user_new:
  url:   /user/new
  param: { module: user, action: new }

user_edit:
  url:   /user/edit/:id
  param: { module: user, action: edit }

user_delete:
  url:   /user/delete/:id
  param: { module: user, action: delete }

article_list:
  url:   /articles
  param: { module: article, action: list }

article_new:
  url:   /article/new
  param: { module: article, action: new }

article_edit:
  url:   /article/edit/:id
  param: { module: article, action: edit }

article_delete:
  url:   /article/delete/:id
  param: { module: article, action: delete }

event_list:
  url:   /events
  param: { module: event, action: list }

event_new:
  url:   /event/new
  param: { module: event, action: new }

event_edit:
  url:   /event/edit/:id
  param: { module: event, action: edit }

event_delete:
  url:   /event/delete/:id
  param: { module: event, action: delete }

file_list:
  url:   /files
  param: { module: file, action: list }

file_new:
  url:   /file/new
  param: { module: file, action: new }

file_edit:
  url:   /file/edit/:id
  param: { module: file, action: edit }

file_delete:
  url:   /file/delete/:id
  param: { module: file, action: delete }

team_list:
  url:   /teams
  param: { module: team, action: list }

team_new:
  url:   /team/new
  param: { module: team, action: new }

team_edit:
  url:   /team/edit/:id
  param: { module: team, action: edit }

team_delete:
  url:   /team/delete/:id
  param: { module: team, action: delete }

delete_from_team:
  url:   /team/deleteUser/:teamId/:userId
  param: { module: team, action: deleteUser }

name_captain:
  url:   /team/nameCaptain/:teamId/:userId
  param: { module: team, action: nameCaptain }

remove_captain:
  url:   /team/removeCaptain/:teamId/:userId
  param: { module: team, action: removeCaptain }

add_team_user:
  url:   /team/addTeamUser/:teamId/:userId
  param: { module: team, action: addTeamUser }

test_sb:
  url:   /sb
  param: { module: homepage, action: sb }

forum:
  url: /forum
  param: { module: forum, action: index }

forum_show:
  url: /forum/:id
  param: { module: forum, action: bigTopicShow }

topic_show:
  url: /topic/:id
  param: { module: forum, action: topicShow }

topic_add:
  url: /topic-add
  param: { module: forum, action: topicAdd }

big_topic_new:
  url: /big-topic/new
  param: { module: forum, action: bigTopicNew }

big_topic_delete:
  url: /big-topic/delete/:id
  param: { module: forum, action: bigTopicDelete }

big_topic_edit:
  url: /big-topic/edit/:id
  param: { module: forum, action: bigTopicEdit }

topic_new:
  url: /topic-new
  param: { module: forum, action: topicNew }

topic_delete:
  url: /topic/delete/:id
  param: { module: forum, action: topicDelete }

topic_edit:
  url: /topic/edit/:id
  param: { module: forum, action: topicEdit }

post_new:
  url: /post/new
  param: { module: forum, action: postNew }

post_delete:
  url: /post/delete/:id
  param: { module: forum, action: postDelete }

post_edit:
  url: /post/edit/:id
  param: { module: forum, action: postEdit }

# default rules
homepage:
  url:   /
  param: { module: homepage, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
