<?php

/**
 * ArticleKeywordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleKeywordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleKeywordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleKeyword');
    }
}