<?php

/**
 * CmsArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orange_ooi
 * @subpackage model
 * @author     Denis Fingonnet <denis.fingonnet@popsiit.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article extends BaseArticle
{
	/**
     * Retrieve picture path
     *
     * @return string avatar path
     */
    public function retrievePictureUrl($web = true)
    {

        $logo = $this->getPicture();

        if (null == $logo) {
            //return null;
            return  sfConfig::get('public_path') . '/images/default-article.png';
        }

        $dirSep = '/';

        return $this->retrieveHashedPictureDirectory($web) . $dirSep . $logo;
    }

    public function retrievePictureWidth()
    {
        $size = getimagesize($this->retrievePictureUrl());
        return $size[0];
    }
    public function retrievePictureHeight()
    {
        $size = getimagesize($this->retrievePictureUrl());
        return $size[1];
    }

     /**
     * Retrieve picture directory only
     *
     * @return string avatar directory only
     */
    public function retrieveHashedPictureDirectory($web = true)
    {
        if ($web) {
            $dirSep = '/';
            $dirPrefix = str_replace(sfConfig::get('sf_web_dir'), '', sfConfig::get('sf_upload_dir'));
            sfContext::getInstance()->getConfiguration()->loadHelpers(array('Url'));

            return public_path(implode($dirSep, array_merge_recursive(array($dirPrefix, 'articles'), str_split($this->getId()))), true);
        } else {
            $dirSep = DIRECTORY_SEPARATOR;
            $dirPrefix = sfConfig::get('sf_upload_dir');

            return implode($dirSep, array_merge_recursive(array($dirPrefix, 'articles'), str_split($this->getId())));
        }
    }

}
