<?php

/**
 * ArticleTable.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Article');
    }

    public function findAllPublishedQuery()
    {
        return $this
            ->createQuery('a')
            ->andWhere('a.is_published = true')
            ->orderBy('a.id DESC');
    }

    public function findAllPublished()
    {
        return $this->findAllPublishedQuery()->execute();
    }

    public function findForAdminQuery()
    {
        return $this
            ->createQuery('a')
            ->orderBy('a.id DESC');
    }
}
