<?php

/**
 * ArticleTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Article');
    }

    public function getArticleQuery()
    {
        return $this
            ->createQuery('a')
            ->andWhere('a.is_published = 1')
            ->andWhere('a.display_to_homepage = 1')
            ->orderBy('a.published_at DESC');
    }

    /**
     * Find by keyword query
     *
     * @param  string $keyword
     * @return Doctrine_Query
     */
    public function findByKeywordQuery($keyword)
    {
        return $this
            ->createQuery('a')
            ->innerJoin('a.Keywords k')
            ->andWhere('k.reference = ?', $keyword);
    }

    /**
     * Find one by keyword
     *
     * @param  string $keyword
     * @return collection of Article
     */
    public function findOneByKeyword($keyword){
        $query = $this
            ->findByKeywordQuery($keyword)
            ->limit(1);

        return $query->execute()->getFirst();
    }

    /**
     * Find by keyword
     *
     * @param  string $keyword
     * @return CmsArticle
     */
    public function findByKeyword($keyword){
        $query = $this
            ->findByKeywordQuery($keyword);

        return $query->execute();
    }
}