<?php

/**
 * BigTopicCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BigTopicCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BigTopicCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BigTopicCategory');
    }
}