<?php

/**
 * BigTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BigTopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BigTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BigTopic');
    }
}