<?php

/**
 * BigTopic
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BigTopic extends BaseBigTopic
{

	public function getNbMessages(){

		return TopicMessageTable::getInstance()->getNbMessagesByBigTopicId($this->getId());

	}

}
