<?php

/**
 * CompetitionSessionTeamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompetitionSessionTeamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompetitionSessionTeamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompetitionSessionTeam');
    }
}