<?php

/**
 * CompetitionSessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompetitionSessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompetitionSessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompetitionSession');
    }
}