<?php

/**
 * CompetitionSessionDisponibilityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompetitionSessionDisponibilityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompetitionSessionDisponibilityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompetitionSessionDisponibility');
    }
}