<?php

/**
 * CoverTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CoverTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CoverTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cover');
    }

    public function findOrdered()
    {
        return $this
            ->createQuery('c')
            ->orderBy('c.position ASC')
            ->execute();
    }
}
