<?php

/**
 * EventTable.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Event');
    }

    public function findAllQuery()
    {
        return $this->createQuery('e')->orderBy('e.date_from DESC');
    }

    public function findNextQuery()
    {
        return $this->createQuery('e')
            ->andWhere('DATE_ADD(e.date_from, INTERVAL 1 DAY) >= NOW() OR DATE_ADD(e.date_to, INTERVAL 1 DAY) >= NOW()')
            ->orderBy('e.date_from DESC');
    }

    public function findToCome($type = 0)
    {
        return $this->createQuery('e')
            ->andWhere('e.date_from >= NOW() OR e.date_to >= NOW()')
            ->andWhere('e.type = ?', array($type))
            ->orderBy('e.date_from DESC')
            ->execute();
    }

    public function findPassed()
    {
        return $this->createQuery('e')
            ->andWhere('e.date_to < NOW()')
            ->orderBy('e.date_from DESC')
            ->execute();
    }

    public function findForAdminQuery()
    {
        return $this
            ->createQuery('e')
            ->orderBy('e.id DESC');
    }
}
