<?php

/**
 * FileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('File');
    }
}