<?php

/**
 * ForumPostTable.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumPost');
    }

    public function findFromDate($date, $user)
    {
        return $this->createQuery('fp')
            ->andWhere('fp.created_at >= ?', array($date))
            ->andWhere('fp.author_id != ?', array($user->getId()));
    }
}
