<?php

/**
 * ForumBigTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumBigTopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumBigTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumBigTopic');
    }
}