<?php

/**
 * ForumTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumTopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumTopic');
    }
}