<?php

/**
 * ForumPostTable.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumPost');
    }

    public function findFromDate($date, $user, $topicId = null)
    {
        $q = $this->createQuery('fp')
            ->andWhere('fp.author_id != ?', array($user->getId()));

        if (null !== $date) {
            $q->andWhere('fp.created_at >= ?', array($date));
        }

        if (null !== $topicId) {
            $q->andWhere('fp.topic_id = ?', array($topicId));
        }

        return $q->execute();
    }
}
