<?php

/**
 * InfoElementTable.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfoElementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfoElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InfoElement');
    }

    public function findOrdered()
    {
        return $this->createQuery('ie')
            ->orderBy('ie.position ASC')
            ->execute();
    }
}
