<?php

/**
 * InformationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InformationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InformationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Informations');
    }
}