<?php

/**
 * Picture
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    esftt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Picture extends BasePicture
{
	/**
     * Retrieve picture path
     *
     * @return string avatar path
     */
    public function retrievePictureUrl($web = true, $thumb = false)
    {

        $img = $this->getName();

        if (null == $img) {
            //return null;
            return  sfConfig::get('public_path') . '/images/default-article.png';
        }

        $dirSep = '/';

        if ($thumb){
            return $this->retrieveHashedPictureDirectory($web) . $dirSep . 'thumb/' .$img;
        } else {
            return $this->retrieveHashedPictureDirectory($web) . $dirSep . $img;
        }

    }

    public function retrievePictureWidth()
    {
        $size = getimagesize($this->retrievePictureUrl());
        return $size[0];
    }
    public function retrievePictureHeight()
    {
        $size = getimagesize($this->retrievePictureUrl());
        return $size[1];
    }

     /**
     * Retrieve picture directory only
     *
     * @return string avatar directory only
     */
    public function retrieveHashedPictureDirectory($web = true)
    {
        if ($web) {
            $dirSep = '/';
            $dirPrefix = str_replace(sfConfig::get('sf_web_dir'), '', sfConfig::get('sf_upload_dir'));
            sfContext::getInstance()->getConfiguration()->loadHelpers(array('Url'));

            return public_path(implode($dirSep, array_merge_recursive(array($dirPrefix, 'gallery/' . $this->getGallery()->getId() . '/pictures'), str_split($this->getId()))), true);
        } else {
            $dirSep = DIRECTORY_SEPARATOR;
            $dirPrefix = sfConfig::get('sf_upload_dir');

            return implode($dirSep, array_merge_recursive(array($dirPrefix, 'gallery/' . $this->getGallery()->getId() . '/pictures'), str_split($this->getId())));
        }
    }
}
