<?php

/**
 * PongScoreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PongScoreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PongScoreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PongScore');
    }

    public function findBests()
    {
    	return $this->createQuery('s')
    		->addSelect('s.playername, s.score')
    		->orderBy('s.score * 1 DESC')
    		->limit(7)
    		->execute();
    }
}