<?php

/**
 * PriceCategoryTable.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PriceCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PriceCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PriceCategory');
    }

    public function findOrdered()
    {
        return $this->createQuery('pc')
            ->orderBy('pc.position ASC')
            ->execute();
    }
}
