<?php

/**
 * PriceElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PriceElementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PriceElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PriceElement');
    }
}