<?php

/**
 * scheduleDayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class scheduleDayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object scheduleDayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('scheduleDay');
    }
}