<?php

/**
 * scheduleCategoryTable.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class scheduleCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object scheduleCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('scheduleCategory');
    }

    public function findOrdered()
    {
        return $this->createQuery('sc')
            ->orderBy('sc.position ASC')
            ->execute();
    }
}
