<?php

/**
 * TopicMessageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TopicMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TopicMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TopicMessage');
    }

    public function getNbMessagesByBigTopicId($btId){

    	$q = $this->createQuery('m')
	    	->innerJoin('m.Topic t')
	    	->andWhere('t.big_topic_id = ?', array($btId));

    	return $q->execute()->count();

    }
}