<?php

/**
 * TopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Topic');
    }
}