# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:

dev:


all:
  
  url:
    facebook: https://www.facebook.com/groups/46831155736/
    twitter: 'https://twitter.com'
    fftt: 'http://www.fftt.com/'
    tennis_de_table: 'http://www.tennis-de-table.com/'

  imagesizes:
    article_picture:
      width: 580
      height: 360

  pagination:
    max_article: 3
    max_event: 2
    max_item_admin: 20

  sf_guard_plugin:
    success_signin_url: "@homepage"
  
  mail:
    to: datcharrye@gmail.com

