# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# article
article_show:
  url: /article/:id
  param: { module: article, action: show }

# comment
new_comment:
  url: /comment/new/
  param: { module: article, action: newComment}

# gallery

gallery_list:
  url: /galleries
  param: { module: gallery, action: list }

gallery_show:
  url: /gallery/:id
  param: { module: gallery, action: show }

# competition

competition_show:
  url: /competition
  param: { module: competition, action: show}

# informations
informations:
  url: /informations
  param: {module: article, action: showInformations}

# forum

forum:
  url: /forum
  param: { module: forum, action: listCategories }

show_big_topics:
  url: /forum/category/:cat_id
  param: { module: forum, action: listBigTopics }

show_topics:
  url: /forum/bt/:big_topic_id
  param: { module: forum, action: listTopics }

show_topic_messages:
  url: /forum/t/:topic_id
  param: { module: forum, action: listMessages }

# user

user_create:
  url: /new-account
  param: { module: user, action: new}

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

blog:
  url: blog/
  param: { module: blog, action: list }

# default rules
homepage:
  url:   /
  param: { module: homepage, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
