# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        esftt
    description:  esftt
    keywords:     esftt
    language:     fr
    #robots:       index, follow

  stylesheets:
    - bootstrap.min.css
    - font-awesome/css/font-awesome.min.css
    - front/s.css

  javascripts:
    - jquery-1.11.1.min.js
    - jquery-ui.min.js
    - bootstrap.min.js
    - script.js


  has_layout:     true
  layout:         layout
