# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        ESFTT - La Frette sur Seine
    description:  "Le site de l'ESFTT, club de tennis de table de la Frette sur Seine"
    keywords:     "ping pong, tennis de table, la frette sur seine, la frette, cormeilles en parisis, esftt"
    language:     fr
    subject:      tennis de table
    category:     sport
    #robots:       index, follow

  stylesheets:
    - bootstrap.min.css
    - bootstrap-theme.min.css
    - font-awesome.min.css
    - swiper.min.css
    - hover-min.css
    - animate.css
    - morris.css
    - front/s.css?v=1.6

  javascripts:
    - jquery.min.js
    - bootstrap.min.js
    - swiper.min.js
    - imagesloaded.pkgd.min.js
    - isotope.pkgd.min.js
    # - masonry.pkgd.min.js
    - raphael.min.js
    - morris.min.js
    # - kendo/kendo.all.min.js
    - script.js?v=1.2
    - pong.js


  has_layout:     true
  layout:         layout
