<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/08/20 13:57:00

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sf_esftt',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
