<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/08/21 14:08:34
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => false,
  'library' => 'gd_mime_type',
),
  'app_sf_admin_dash_web_dir' => '/sfAdminDashPlugin',
  'app_sf_admin_dash_image_dir' => '/sfAdminDashPlugin/images/icons/',
  'app_sf_admin_dash_default_image' => 'config.png',
  'app_sf_admin_dash_dashboard_url' => '@homepage',
  'app_sf_admin_dash_resize_mode' => 'thumbnail',
  'app_sf_admin_dash_site' => 'esftt',
  'app_sf_admin_dash_include_path' => true,
  'app_sf_admin_dash_include_assets' => true,
  'app_sf_admin_dash_include_jquery' => false,
  'app_sf_admin_dash_include_jquery_no_conflict' => false,
  'app_sf_admin_dash_login_route' => '@sf_guard_signin',
  'app_sf_admin_dash_logout' => true,
  'app_sf_admin_dash_logout_route' => '@sf_guard_signout',
  'app_sf_admin_dash_categories' => array (
  'CMS' => 
  array (
    'items' => 
    array (
      'Articles' => 
      array (
        'url' => 'article',
        'image' => 'addedit.png',
      ),
    ),
  ),
  'Utilisateur' => 
  array (
    'items' => 
    array (
      'Utilisateurs' => 
      array (
        'url' => 'sf_guard_user',
        'image' => 'users.png',
      ),
    ),
  ),
  'Gallerie' => 
  array (
    'items' => 
    array (
      'Gallery' => 
      array (
        'url' => 'gallery',
        'image' => 'addedit',
      ),
      'Picture' => 
      array (
        'url' => 'picture',
        'image' => 'addedit',
      ),
    ),
  ),
),
  'app_imagesizes_big' => array (
  'width' => 1440,
  'height' => 960,
),
  'app_imagesizes_small' => array (
  'width' => 508,
  'height' => 800,
),
  'app_imagesizes_slides' => array (
  'width' => 427,
  'height' => 240,
),
  'app_imagesizes_slides_old' => array (
  'width' => 504,
  'height' => 320,
),
  'app_imagesizes_ideas' => array (
  'width' => 646,
  'height' => 358,
),
  'app_imagesizes_miniideas' => array (
  'width' => 323,
  'height' => 179,
),
  'app_imagesizes_fit' => array (
  'width' => 608,
  'height' => 348,
),
  'app_imagesizes_picture' => array (
  'width' => 800,
  'height' => 600,
),
));
