<?php

/**
 * sfGuardUserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    public function findAvailableBySessionId($session_id){

    	$q = $this->createQuery('u')
    	->innerJoin('u.CompetitionSessionDisponibility csd')
    	->andWhere('csd.is_available = ?', array(true));

    	return $q->execute();

    }

    public function findUnAvailableBySessionId($session_id){

    	$q = $this->createQuery('u')
    	->innerJoin('u.CompetitionSessionDisponibility csd')
    	->andWhere('csd.is_available = ?', array(false));

    	return $q->execute();

    }
}