generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      filter:
        display: [username, email_address, is_active]

      list:
        title:   User list
        display: [=username, first_name, last_name, email_address, is_active]

      form:
        class: sfGuardUserBackendForm
        display:
          "User":                   [first_name, last_name, email_address, username, avatar]

      edit:
        title: Editing User "%%username%%"

      new:
        title: New User
