generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Article
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          article
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        display: [=title, is_published, published_at]
      filter:
        display: [is_published, published_at]
      form:
        class: ArticleBackendForm
      edit:    ~
      new:     ~
