<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/08/12 13:13:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sf_esftt',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
