<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/08/12 13:13:45
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'signinhybridprocess' => 
  array (
    'is_secure' => false,
  ),
  'signinhybrid' => 
  array (
    'is_secure' => false,
  ),
  'signinprofilhybrid' => 
  array (
    'is_secure' => false,
  ),
  'signinajax' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
