Article:
  tableName: article
  actAs:
    Timestampable: ~
  columns:
    title:
      type: string(255)
      notnull: true
    sub_title:
      type: string(255)
    content:
      type: clob
      notnull: true
    is_published:
      type: boolean
      notnull: false
      default: false
    published_at:
      type: timestamp
      notnull: true
    illustration:
      type: string(255)

sfGuardUser:
  columns:
    avatar:
      type: string(255)
  relations:
    Teams:
      class: Team
      refClass: UserTeam
      local: user_id
      foreign: team_id
      foreignAlias: Teams

Team:
  columns:
    name:
      type: string(255)
  relations:
    Users:
      class: sfGuardUser
      refClass: UserTeam
      local: team_id
      foreign: user_id
      foreignAlias: Users

UserTeam:
  columns:
    user_id:
      type: integer
    team_id:
      type: integer
  relations:
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      foreignAlias: UserTeams
    Team:
      class: Team
      local: team_id
      foreign: id
      foreignAlias: UserTeams


